const baseCss = `:root{color-scheme:dark;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;background:#0d0c13;color:#f2efff}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 80% 0,#292044 0,transparent 38%),#0d0c13}header,main{width:min(1100px,calc(100% - 32px));margin:auto}header{display:flex;align-items:center;justify-content:space-between;padding:32px 0 18px;border-bottom:1px solid #302b3d}h1{margin:.2rem 0;font-size:clamp(1.8rem,4vw,3rem)}h2{font-size:1rem;color:#aaa2bd}small{color:#9189a5;letter-spacing:.12em}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin:24px 0}article,section:not(.grid){padding:20px;border:1px solid #302b3d;border-radius:12px;background:#17141fbb}article strong{display:block;font-size:1.65rem;margin-top:10px}.good{color:#6ee7a8}.bad{color:#ff7c8b}.warn{color:#ffd166}button,.button{border:1px solid #7665a9;border-radius:8px;padding:10px 14px;background:#6d4bc3;color:white;text-decoration:none;font:inherit;cursor:pointer}.login{min-height:100vh;display:grid;place-content:center;text-align:center;gap:12px}.login p{color:#aaa2bd}.moon{font-size:5rem;color:#c5afff}pre{white-space:pre-wrap;color:#c5bdd8;line-height:1.6}#error{color:#ff7c8b;margin-top:18px}`;

export const loginPage = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lunafications Admin</title><style>${baseCss}</style></head><body><main class="login"><div class="moon">☾</div><h1>Lunafications</h1><p>Private operations dashboard</p><a class="button" href="/oauth/login">Sign in as @imlunahey.com</a></main></body></html>`;

export const dashboardPage = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lunafications Dashboard</title><style>${baseCss}</style></head><body><header><div><small>OPERATIONS</small><h1>Lunafications</h1></div><form method="post" action="/logout"><button>Sign out</button></form></header><main><div id="error"></div><section class="grid" id="cards"></section><section><h2>Runtime details</h2><pre id="details">Loading…</pre></section></main><script>
const fmtBytes=n=>{const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]};
const fmtTime=n=>n?new Date(n).toLocaleString():'Never';
async function refresh(){try{const r=await fetch('/api/status',{credentials:'same-origin',cache:'no-store'});if(r.status===401){location.href='/';return}if(!r.ok)throw new Error('Status '+r.status);const s=await r.json();document.querySelector('#error').textContent='';const cards=[['Jetstream',s.jetstream.connected?'Connected':'Disconnected',s.jetstream.connected?'good':'bad'],['Pending',s.queue.pending,''],['Retrying',s.queue.retrying,s.queue.retrying?'warn':''],['Delivered · 48h',s.queue.deliveredMarkers,''],['RSS memory',fmtBytes(s.memory.rss),''],['Heap used',fmtBytes(s.memory.heapUsed),''],['Block users',s.subscriptions.blockUsers,''],['List users',s.subscriptions.listUsers,''],['Post users',s.subscriptions.postUsers,'']];document.querySelector('#cards').innerHTML=cards.map(c=>'<article><small>'+c[0]+'</small><strong class="'+c[2]+'">'+c[1]+'</strong></article>').join('');document.querySelector('#details').textContent=JSON.stringify({uptimeSeconds:s.uptimeSeconds,jetstreamCursor:s.jetstream.cursor,lastJetstreamEvent:fmtTime(s.jetstream.lastEventAt),lastQueueRun:fmtTime(s.queue.lastRunAt),lastDelivery:fmtTime(s.queue.lastDeliveryAt),jetstreamError:s.jetstream.lastError,deliveryError:s.queue.lastError,memory:s.memory},null,2)}catch(e){document.querySelector('#error').textContent='Unable to refresh: '+e.message}}
refresh();setInterval(refresh,3000);
</script></body></html>`;
